// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteContent: typeof import('./src/components/SiteContent/index.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter/index.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader/index.vue')['default']
  }
}
