import { LevelName } from "./LevelName";

export interface JobResponse {
    id: number|undefined,
    jobTypeId: number|undefined,
    companyId: number|undefined,
    levelName: LevelName|undefined,
    careerId: number|undefined,
    workingFormId: number|undefined,
    quantity: number|undefined,
    rangeSalaryMin: number|undefined,
    rangeSalaryMax: number|undefined,
    information: string|undefined,
    status: string|undefined,
    customRange: boolean|undefined,
    thumbnail: string|undefined,
    thumbnailAfter: string|undefined,
    jobTypeName: string|undefined,
    companyName: string|undefined,
    careerName:  string|undefined,
    workingFormName: string|undefined,
    color: string|undefined,
    title: string|undefined,
    voucherInfo: string|undefined,
    agencyId: number|undefined,
    agencyName: string|undefined,
    avatarUrl: string|undefined,
    avatarUrlAfter: string|undefined,
    tags: string[]|string|undefined,
    reasonForChoosing: string[]|string|undefined,
}